### ISSUE TITLE
Not all events are getting captures

### ISSUE THREAD

**Issue by loctrice** [jsonmaur/stripe-local#5]
I tried setting the interval to 3000 to see if that solved the problem, but we aren't getting all the web hook events captured. It's pretty consistent about missing part of them. A lot of these events look like they happen in the same second via the dashboard so maybe adding a tolerance to the last timestamp could help?

**Comment by jsonmaur** [comment]
Fixed via https://github.com/jsonmaur/stripe-local/pull/6.
